//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperVMs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyperVMs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menu_Exit {
            get {
                return ResourceManager.GetString("menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string menu_OpenSettings {
            get {
                return ResourceManager.GetString("menu_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shell.
        /// </summary>
        internal static string menu_OpenShell {
            get {
                return ResourceManager.GetString("menu_OpenShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power States.
        /// </summary>
        internal static string menu_PowerStates {
            get {
                return ResourceManager.GetString("menu_PowerStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get IP Address of the VM.
        /// </summary>
        internal static string message_NoIP {
            get {
                return ResourceManager.GetString("message_NoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperVMs.
        /// </summary>
        internal static string title_Main {
            get {
                return ResourceManager.GetString("title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Open Shell.
        /// </summary>
        internal static string title_VMOpenShell {
            get {
                return ResourceManager.GetString("title_VMOpenShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Status.
        /// </summary>
        internal static string title_VMStatus {
            get {
                return ResourceManager.GetString("title_VMStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to shell into the VM.
        /// </summary>
        internal static string tooltip_OpenShell {
            get {
                return ResourceManager.GetString("tooltip_OpenShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Start the VM.
        /// </summary>
        internal static string tooltip_StartVM {
            get {
                return ResourceManager.GetString("tooltip_StartVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Stop the VM.
        /// </summary>
        internal static string tooltip_StopVM {
            get {
                return ResourceManager.GetString("tooltip_StopVM", resourceCulture);
            }
        }
    }
}
